baseURL = 'https://fgc-ar.netlify.app/'
languageCode = 'it'
defaultContentLanguage = 'it'
title = 'FGC Arezzo'
theme = 'blowfish'


[params]
  colorScheme = 'slate'
  defaultAppearance = 'light'
  autoSwitchAppearance = true
  enableSearch = true
  showScrollToTop = true
  logo = "images/logo_vet.png"

[params.homepage]
  layout = 'custom'
  
[markup.goldmark.renderer]
  unsafe = true

[params.article]
  showDate = false
  showReadingTime = false
  showWordCount = false
  
[[menus.main]]
  name = 'Libreria'
  url = '/libreria/'
  weight = 1

[[menus.main]]
  name = 'Iniziative'
  url = '/iniziative/'
  weight = 2

[[menus.main]]
  name = 'Cineforum'
  url = '/cineforum/'
  weight = 3

  [[menus.main]]
  name = 'Calendario'
  url = '/calendario/'
  weight = 5
  
[[menus.main]]
  name = 'Unisciti'
  url = '/unisciti/'
  weight = 4
